// punishments.js
// Expanded punishment lists for each difficulty level

const PUNISHMENTS = {
  Easy: [
    "Sit on your hands until your next turn.",
    "Speak only when spoken to for the next full round.",
    "Remove one sock with your teeth.",
    "Say 'I am [opponent\'s name]\'s toy' three times out loud.",
    "Hold a penny between your butt cheeks for one full turn.",
    "Kiss the floor.",
    "Let your opponent rename you for the next 3 rounds.",
    "Stay on your knees for the next turn.",
    "Let opponent tuck your shirt into your underwear.",
    "Draw a small heart or collar on your chest or neck with a marker.",
    "Hold your tongue out for 30 seconds without laughing or pulling it back in.",
    "Whisper 'please punish me' in your opponent\'s ear.",
    "Text yourself 'I\'m a good little pet' and show your opponent.",
    "Balance an object (book, cup, etc.) on your head for 1 minute.",
    "Speak in third person for the next two turns.",
    "Roll over and beg like a dog.",
    "Let your opponent give you a silly nickname for the next hour.",
    "Keep your hands behind your back until your next action.",
    "Put on an item of clothing backward.",
    "Hold an ice cube in your hand while staying silent.",
    "Let your opponent boop your nose and say 'mine.'",
    "Stand in the doorway like you\'re being displayed for 30 seconds.",
    "Rub your own face like you\'re being petted.",
    "Stick out your tongue and say 'I deserve worse.'",
    "Write 'loser' on your foot and show it.",
    "Say 'I\'ll be good' every time your opponent looks at you for the next round.",
    "Only crawl to change your position until your next turn.",
    "Nod and say 'yes, [title]' every time you\'re spoken to until the next round.",
    "Let your opponent adjust your posture exactly how they want.",
    "Keep your eyes lowered until you\'re given permission to look up.",
    "Make up a cringey pet name for yourself and say it out loud.",
    "Spell the word 'obedient' using your body like you\'re in a cheer routine.",
    "Say 'I\'m a little shy toy' while hiding your face.",
    "Let your opponent take a picture of your most embarrassed face (non-nude).",
    "Read aloud a mock 'confession' written by your opponent.",
    "Wag your butt like a tail and pant.",
    "Balance a small item on your nose like a puppy.",
    "Crawl in a circle twice and bark softly.",
    "Purr while being pat on the head for 10 seconds.",
    "Wear something on your wrist or neck like a leash for one turn.",
    "Hold your arms out straight for 45 seconds.",
    "Sit cross-legged and keep your hands flat on your thighs.",
    "Stand facing the wall with hands behind your head for 1 minute.",
    "Lie on the floor with your hands behind your back for 30 seconds.",
    "Put an ice cube in your sock until it melts or the next turn.",
    "End every sentence with 'if I\'m allowed.'",
    "Recite the alphabet backward (or try).",
    "Repeat 'I serve. I obey. I blush.' three times.",
    "Say your opponent\'s name in a flirty voice 5 times.",
    "Make up a theme song about being punished and sing the chorus.",
    "Stay silent until your opponent snaps their fingers.",
    "Ask for permission to sit, even if you don\'t plan to.",
    "Stand with your arms behind your back while your opponent circles you.",
    "Let your opponent pick your pose for 1 minute and freeze like a statue.",
    "Thank your opponent for punishing you, and mean it.",
    "Say 'I secretly like being punished' in your most embarrassed voice.",
    "Mime getting spanked while looking bashful.",
    "Blush on command. If you can\'t, fake it.",
    "Describe your 'most humiliating fantasy' using only five words.",
    "Write 'punishable' on your hand and keep it visible for the next round.",
    "Crouch like a bunny and stay still until your opponent tells you to move.",
    "Be 'on display'—pose cutely or suggestively for 30 seconds.",
    "Meow twice every time you move until your next turn.",
    "Sniff your own shirt collar or armpit like you\'re being checked.",
    "Lick your own hand and pretend it was someone else\'s.",
    "Sit with your legs spread wide (clothed) and hold position for 1 minute.",
    "Keep your arms above your head for 1 full turn.",
    "Use your toes to pick up an object and hand it to your opponent.",
    "Place a small object under your shirt and let it stay there for 2 rounds.",
    "Sit on the ground with your knees up, arms wrapped around them, and rock for 30 seconds.",
    "Speak in a fake accent for the next 3 sentences.",
    "Make up a motto for yourself as a submissive.",
    "Say your favorite dessert in the sexiest voice you can manage.",
    "Narrate your own punishment like it\'s a nature documentary.",
    "Say 'I lost because I\'m cute and weak' with a giggle.",
    "Keep your palms visible and open at all times until your next turn.",
    "Sit exactly where your opponent points—floor, couch, etc.",
    "Say 'Whatever you say, I\'ll do' three times in a row without smiling.",
    "Stay in physical contact with your opponent (hand, foot, shoulder) until next round.",
    "Ask 'What would please you most right now?' and accept their answer respectfully.",
    "Name 3 places you\'d hate to be punished in public. Say them out loud.",
    "Pretend to be scolded and respond with 'Yes, I deserve it' three times.",
    "Stick your tongue out, cross your eyes, and say 'I\'m so dumb, it\'s cute.'",
    "Rate your own obedience on a scale from 1 to 10—but explain why it\'s so low.",
    "Say: 'Punishments make me wet/hard and ashamed.' Then cover your face.",
    "Let your opponent 'reposition' you like a doll or a display figure.",
    "Place an object on your back and try to stay still so it doesn\'t fall.",
    "Bark each time your opponent says a command word (they choose it).",
    "Crawl to your opponent with something in your mouth and drop it at their feet.",
    "Put your hands together like paws and stay that way until the end of the turn.",
    "Stand on your toes for 30 seconds. Each second you wobble = one extra second.",
    "Lay belly-down and stay perfectly still for 45 seconds.",
    "Sit with one hand behind your back and one on your mouth for one full turn.",
    "Put your feet or hands flat on a cold surface and keep them there for 1 minute.",
    "Push your hands between your thighs and hold them there—no fidgeting.",
    "Recite a made-up school pledge for 'The Academy of Obedience.'",
    "Narrate your defeat like you\'re the sad loser in a drama.",
    "Pretend you\'re auditioning for the role of 'perfect toy.' Sell it.",
    "Try to say 'I don\'t deserve this' without laughing or blushing.",
    "Choose one body part and confess something humiliating about it.",
    "Count to 50 in a whisper while balancing on one foot.",
    "Hold your breath while your opponent counts to 20.",
    "Slowly lower yourself to your knees over a count of 10.",
    "Clap once every 5 seconds for a full minute—each clap must be followed by 'Good toy.'",
    "Ask your opponent for a 15-second task and obey it immediately, no questions.",
    "Rub something cold on your lower back and describe how it feels.",
    "Sit still while your opponent hovers their hand an inch from your face—don\'t move.",
    "Close your eyes and identify 3 textures touching your body.",
    "Allow your opponent to breathe or whisper something into your ear.",
    "Press your tongue to something cold or smooth and say how it tastes.",
    "List three punishments you\'re dying to receive, and then ask to be denied all of them.",
    "Hold your hand near your own thigh or crotch—but never make contact.",
    "Beg to be allowed to touch your favorite spot. If they say no, say 'Thank you.'",
    "Place your own finger on your lips and whisper, 'Not yet.'",
    "Write 'edge' on your palm and stare at it silently for one full turn.",
    "Act like a wind-up toy: let your opponent 'wind' you up, then do 5 silly movements.",
    "Pose like a calendar model for pets—sassy, smug, or cute.",
    "Ask your opponent for a reward… then tell them why you don\'t deserve it.",
    "Declare what 'level' submissive you are, like it\'s a video game stat.",
    "Roll an invisible die and pretend it determines your fate—react accordingly.",
    "Act like a robot taking orders from your opponent for one turn.",
    "Sit cross-legged with your tongue out for 30 seconds.",
    "Every time your opponent speaks for the next minute, you must whisper 'yes.'",
    "Mime licking your opponent\'s boots, slowly and dramatically.",
    "Ask, 'Can I be punished harder next time?'",
    "Make your best 'begging face' and hold it for 10 seconds.",
    "Try to balance a pillow on your head while crawling across the room.",
    "Say 'I need structure. I need discipline. I need you.'",
    "Crouch like a frog and stay there for one minute.",
    "Give yourself a nickname and beg your opponent to call you by it.",
    "Say 'I\'m trained and tamed' while touching your collarbone.",
    "Press your forehead to the floor for 20 seconds.",
    "Stay completely still while your opponent walks around you.",
    "Spell the word 'humiliate' out loud while looking at the floor.",
    "Ask to be leashed, even if no leash is present.",
    "Count from 10 to 1 in a moaning, drawn-out voice.",
    "Let your opponent 'inspect' you without speaking.",
    "Pretend to be activated by a single word your opponent picks.",
    "Gently tap your own cheek every time you mess up a sentence.",
    "Ask your opponent to call you by your most embarrassing pet name.",
    "Lay flat on your back and pretend to be turned off until your opponent reactivates you.",
    "Make a sound effect for every movement you make for the next minute.",
    "Bow every time you enter or leave a space for the next 2 turns.",
    "Stay one step behind your opponent wherever you go for one round.",
    "Whimper once every 15 seconds until told to stop.",
    "Say, 'I\'m ready to be molded into whatever you need.'",
    "Shake your butt three times and say 'Trained and proud.'",
    "Bite your finger and say 'I\'m naughty and I know it.'",
    "Ask, 'Can I prove myself to you again?'",
    "Say your opponent\'s name like a secret crush.",
    "Let your opponent assign you a simple task—and thank them afterward.",
    "Act like you\'re being patted and say 'good toy' every 5 seconds.",
    "Say 'Please don\'t make me enjoy this,' then smile.",
    "Crawl to your opponent and rest your head on their knee.",
    "Repeat 'I am shaped by your hands' until interrupted.",
    "Lick your own lips slowly and say 'I\'ll behave.'",
    "Pace in a circle like a trained show pet.",
    "Say 'This is humiliating, and I love it.'",
    "Act like you\'re being scolded and nod shamefully.",
    "Make your body into a letter 'S' on the floor.",
    "Hold your breath while being stared at.",
    "Ask for feedback on your posture.",
    "Keep your fingers laced behind your head until your opponent lets you go.",
    "Meow every time you change position until the next round.",
    "Hold one shoe in your mouth handle (or pretend to).",
    "Keep your hands folded like a good student.",
    "Ask for 'just one small punishment' in the cutest voice you can.",
    "Shiver on command.",
    "Let your opponent rest their foot or hand on you for 1 minute.",
    "Announce 'I am nothing but a canvas for your power.'",
    "Tuck your hands into your waistband and walk 3 steps.",
    "Say 'I need structure' and bow your head.",
    "Rest your chin on your opponent\'s hand or lap (if permitted).",
    "Keep your mouth open for 15 seconds while kneeling.",
    "Chant 'obedient, obedient, obedient' quietly.",
    "Rub your face on the carpet or couch and say 'pet behavior.'",
    "Let your opponent give you a new role: pet, object, toy, etc.",
    "Ask your opponent for instructions on how to sit.",
    "Say 'I am learning to listen' while staying silent.",
    "Place your hands flat on a table and don\'t move them for 2 minutes.",
    "Flop on the ground and say 'I\'m yours to pick up.'",
    "Ask for your punishment in rhyme form.",
    "Hum a lullaby while curled into a ball.",
    "Repeat 'yes' after every statement your opponent makes for 1 round.",
    "Crouch and stare at the floor like you\'ve been put in time out.",
    "Let your opponent pose you like a doll and hold still.",
    "Ask to be told what you\'re good for.",
    "Gently slap your own cheek and whisper 'Obey.'",
    "Make your lips into a kissy face until dismissed.",
    "Say 'I am trained and treasured' like a mantra.",
    "Repeat 'I am below you' softly and reverently.",
    "Act like you\'re being auctioned and describe your 'features.'",
    "Lay with your arms above your head and stay still.",
    "Repeat 'please use me' until interrupted.",
    "Let your opponent tap your nose every time you speak.",
    "Stick your tongue out until your opponent says 'down.'",
    "Mime being walked on a leash.",
    "Kneel with your hands in prayer and whisper 'I obey.'",
    "Rub your own thighs and say 'I\'m patient.'",
    "Blink twice slowly and say 'I\'m thinking obedient thoughts.'"
  ],
  Medium: [
    "Moderate spanking",
    "Sensory play (ice cube, feather, etc.)",
    "Light impact play (hand or soft object)",
    "Moderate bondage (hands tied behind back)",
    "Sensual domination (winner gives a command)",
    "Teasing and denial (no touching for 1 round)",
    "Loser must remove a piece of clothing",
    "Winner gets to blindfold the loser for a round",
    "Loser must give the winner a compliment",
    "Winner gets to tickle the loser for 15 seconds",
    "Loser must do a slow spin for the winner",
    "Winner gets to whisper something to the loser",
    "Loser must act out a fantasy for 30 seconds",
    "Winner gets to choose the next punishment",
    "Loser must hold a pose for 20 seconds"
  ],
  Hard: [
    "Insert a plug and stay kneeling, ass raised, for five full minutes—no movement.",
    "Spread your pussy or ass lips and say 'this is my use, not my choice.'",
    "Let your opponent slap your bare cunt or balls 10 times—thank them after each.",
    "Gag yourself with your underwear and kneel, mouth open, until told to close.",
    "Sit on a hard surface with your legs spread wide and hold that pose for 2 minutes.",
    "Edge while fully exposed—every moan earns a slap.",
    "Use a vibrator or pressure on your pussy/ass until tears start forming—then stop.",
    "Crawl on all fours, hole visible, and beg to be used without protection.",
    "Let your opponent spit into your hole (or pretend to), then seal it with a plug.",
    "Rub an ice cube against your clit or rim your own ass with it.",
    "Slap your own pussy or asshole and say 'obedience is learned through pain.'",
    "Face the wall, plug in, and stay there holding your cheeks apart.",
    "Let your opponent use a toy on your cunt/ass for 60 seconds without mercy.",
    "Show your hole to the opponent and say, 'I surrender to your will.'",
    "Lick your fingers clean after rubbing your pussy or playing with your ass.",
    "Smack your own clit or asshole each time you say 'I want to be broken.'",
    "Get your face sat on or stepped over—no flinching, no speaking.",
    "Beg for one orgasm you're not allowed to have—ask again, softer.",
    "Keep a toy inside and sit directly on it without moving for 3 minutes.",
    "Rub piss on your pussy lips or around your asshole—then hold eye contact.",
    "Lie back with your legs up and say 'I'll take what I'm given.'",
    "Let your opponent press their foot to your pussy or ass and grind.",
    "Edge using your finger, toy, or surface—don't stop unless told.",
    "Present your cunt/ass and offer your mouth at the same time—say 'choose your hole.'",
    "Push fingers inside yourself and hold them in while being degraded.",
    "Get tied up and left exposed while your opponent talks about what they could do.",
    "Crawl ass-first across the floor and beg to be filled.",
    "Lick a toy or finger while your ass or cunt is being spanked.",
    "Finger your pussy or ass while your opponent counts backwards from 30—stop on zero.",
    "Ask for your clit or hole to be punished directly—let them choose how.",
    "Cry out one humiliating phrase with every thrust or rub.",
    "Lay on your back, feet to your ears, and stay exposed until next round.",
    "Let your opponent insert a toy, remove it, then gag you with it.",
    "Moan while being used—if your pitch drops, you're punished.",
    "Show your hole in the mirror, say 'worthless and open,' and hold the gaze.",
    "Hold your cheeks apart while your opponent inspects your hole in silence.",
    "Be instructed to finger yourself in public risk position (balcony, near window).",
    "Suck on a plug or toy while holding your legs spread wide.",
    "Rub your asshole or clit and describe how each touch makes you more submissive.",
    "Lick something off your opponent's shoe or foot while plugged.",
    "Keep your tongue pressed to your clit or rim your own asshole for 30 seconds.",
    "Let your opponent write 'fuckhole' or 'cumdump' across your pelvis or lower back.",
    "Spank your own cunt or hole five times and say 'harder, please' after each.",
    "Crawl with a plug in and a toy in your mouth like it's a leash.",
    "Get slapped every time you hesitate while using your own hole.",
    "Pretend to be tied and pretend to resist—then cry 'please don't stop.'",
    "Rub your face against your own thighs, whispering 'this body is not mine.'",
    "Say 'this hole is yours to destroy' and finger yourself while you say it.",
    "Press your face into a dirty object (floor, sock, clothing) and beg to be used like it.",
    "Hold still while your opponent whips, spanks, or gropes you from behind.",
    "Get 30 spanks—each one must be counted aloud while maintaining position.",
    "Tie a rope or belt around your thighs to keep them spread, and kneel silently.",
    "Place a clothespin or clamp on a sensitive spot and hold still for 2 minutes.",
    "Edge while kneeling, ass in the air—stop instantly if you're touched.",
    "Say 'Please ruin my hole' while rubbing it and staying in eye contact.",
    "Grip your own throat or hair tightly while repeating 'I want to obey.'",
    "Present your hands to be bound, then sit motionless for five minutes.",
    "Spread your legs and stay still—your opponent will tease with no permission to squirm.",
    "Get paddled, whipped, or slapped with a chosen tool until you cry out three times.",
    "Say 'Use me. Break me. Make me beg.'—then obey the next command.",
    "Sit on a plug or insert a toy and recite your last three failures as a submissive.",
    "Your hole is off-limits for the rest of the game unless earned—write it on yourself.",
    "Stay silent for the next full round, even during punishment or stimulation.",
    "Accept a gag (or simulate one) and try to complete a degrading task while silenced.",
    "Edge yourself while counting to 100 out loud, one second at a time.",
    "Take 3 hard slaps on your cunt/ass every time you touch yourself without permission.",
    "Sit with a spoon of water on your head—spill it and start over—while your hole is teased.",
    "Say 'You're the reason I'm nothing but a body' and keep your head down.",
    "Ask for permission before every word spoken for 10 minutes—each failure earns a slap.",
    "Let your opponent smack your clit or asshole in rhythm while you count.",
    "Stay frozen with your tongue out—your opponent can spank, rub, or ignore you.",
    "Present your pussy or ass and be denied touch for 10 full minutes.",
    "Plugged and gagged, you must 'nod yes' to everything you're asked—even insults.",
    "Be restrained and edged for 5 minutes—but no begging allowed.",
    "Accept any two punishment tools (e.g. crop, paddle, hand) and take 15 swats total.",
    "Stand still while your opponent threatens to punish your favorite spot—but delays it.",
    "Let your opponent tie your hands, then edge you without release.",
    "Touch your hole as if you're about to be used—then freeze and beg not to be.",
    "Lay flat, fully exposed, while your opponent inspects you like a broken toy.",
    "Ask to be blindfolded or placed in the dark, then listen to your opponent move around you.",
    "Press your face into the wall while your opponent uses you or waits.",
    "Attempt to masturbate with no movement below the waist—failure = punishment.",
    "Be whipped, slapped, or scratched while repeating 'I will obey better.'",
    "Crawl with clamps on your nipples or ass cheeks, begging for mercy.",
    "Open your mouth and be slapped every time you try to close it.",
    "Let your opponent mark you with a humiliating label and punish any attempt to hide it.",
    "Rub your ass or pussy on a cold surface and moan for 30 seconds.",
    "Present your whole body, plug in, while being insulted and ignored.",
    "Edged five times in a row with no orgasm allowed—each denial earns a slap.",
    "Simulate being punished in public—moan and react as if being watched.",
    "Stay on display, legs spread, with clamps or pressure, until your opponent dismisses you.",
    "Obey a set of verbal commands without hesitation—hesitate once and you get paddled.",
    "Repeat 'I serve pain' with every stroke of your punishment.",
    "Stand with legs apart, arms above head, and let your opponent do as they like.",
    "Plug yourself and beg for it to be bigger.",
    "Suck a toy while someone teases your hole—failure to maintain pace = punishment.",
    "Hold your own wrists behind your back and don't move as you're played with.",
    "Beg your opponent to break your hole for their amusement.",
    "Stay gagged and plugged in corner, touching nothing, until a command is given.",
    "Ask 'How much pain do I deserve today?'—accept their answer fully."
  ],
  Extreme: [
    "Be hogtied with a plug in, gagged, and displayed for full inspection—no movement allowed.",
    'Crouch in the doorway, ass or pussy exposed, and beg to be walked like a fuckpet.',
    'Simulate a triple hole use: plug in, mouth gagged, hands spreading the remaining hole.',
    'Stay face-down, tongue out, while your opponent fucks or fists your ass or cunt.',
    'Plug yourself, crawl in a circle, and chant "one hole, one purpose."',
    'Be bound and used without asking—you don\'t speak unless asked a question.',
    'Get slapped each time you breathe too loud while gagged, ass exposed.',
    'Open your legs, insert the largest toy you can handle, and hold for 3 minutes.',
    'Sit on the floor, hands behind your back, while your opponent verbally degrades your holes.',
    'Be face-fucked (or simulate it with toy/gag), no eye contact allowed, hands pinned.',
    'Edge five times while bound—moan once and you\'re denied release.',
    'Stay bent over with your ass held open—gag in, plug in, blindfolded.',
    'Receive a 3-hole slap: one for the mouth, one for the ass, one for the cunt.',
    'Crawl to a window or balcony, tongue out, and simulate begging for public use.',
    'Be tied with your legs over your head, stuffed with toys, and left to drool.',
    'Spread and hold your own holes open while your opponent circles you silently.',
    'Ask, "Which hole deserves pain, and which deserves shame?"—let your opponent decide.',
    'Have your name replaced—only respond to "fuckhole," "slut," or "it" for three rounds.',
    'Be used by two players (or simulate it): one takes your mouth, the other takes your hole.',
    'Crawl with clamps on your nipples or labia, plug inside, gag in, posture held.',
    'Get edged while standing on tiptoe—drop down early, take five hard slaps.',
    'Say, "Use me until I break or blackout," while your opponent grips your throat.',
    'Stay silent for an entire scene. Moan once and your next orgasm is ruined.',
    'Lick the floor or a shoe while someone toys your hole—say "this is my worth."',
    'Stay locked in place, fully stuffed, while your opponent drinks or relaxes nearby.',
    'Be placed kneeling with forehead to the ground—plugged, leashed, wrists tied.',
    'Simulate being spitroasted: one toy in mouth, one in ass or pussy, hands behind you.',
    'Kneel, hands on head, hole leaking—stay frozen while degraded or walked over.',
    'Receive impact play (spanks, slaps, crops) to a single spot until it bruises.',
    'Be blindfolded and edged until you\'re shaking, then denied without a word.',
    'Be stood against the wall, arms behind your back, while your hole is used or inspected.',
    'Hold a dildo or gag in your mouth and offer your body like furniture.',
    'Get used, then plugged, then told to crawl across the room without dripping.',
    'Gagged and spread, simulate being left on a stage for strangers to use.',
    'Grind your hole against an object while chanting a humiliating phrase—loudly.',
    'Crouch naked on a balcony or in front of a window, gag in, body exposed.',
    'Be given a countdown while fucked—if you don\'t cum on cue, you\'re punished.',
    'Simulate breath play while your face is pinned—gag in, hands restrained.',
    'Be placed ass-up over furniture, plugged, gagged, and unable to see who\'s watching.',
    'Grind into a pillow or toy while repeating "fuckhole first, feelings never."',
    'Be called "property," "equipment," or "livestock" and treated accordingly—positioned, used, dismissed.',
    'Beg to be stretched beyond your current limit—then hold it until tears come.',
    'Stay fully plugged and gagged while your opponent pisses into a bowl beside you.',
    'Be leashed and walked into the bathroom, where you\'re ordered to kneel beside the urinal.',
    'Be held in front of a mirror, dripping, hole open, while told "you\'re only a urinal now."',
    'Gagged with piss-soaked panties or cloth and made to sit, legs open.',
    'Watch your opponent piss—you\'re not allowed to speak, just kneel and stare.',
    'Be pissed on, then immediately spanked until red—\'waste first, punishment second.\'',
    'Lick up your own piss from the floor—slowly, in silence.',
    'Plug in, hole exposed, and beg to be refilled or ruined, loudly and repeatedly.',
    'Simulate a gangbang: lie on your back, legs wide, moaning as if holes are used in rotation.',
    'Be tied down, holes exposed, and forced to beg for "just one more user."',
    'Get edged by multiple hands or toys—one mistake, and your orgasm is ruined.',
    'Hold a plug in your ass while your pussy is slapped 10 times—switch if male.',
    'Stay on your knees for 10 minutes, gagged, arms behind back—if you fall, you\'re caned.',
    'Simulate getting fucked while someone feeds your mouth—moan like it\'s your purpose.',
    'Be blindfolded, gagged, and laid out as a cumdump—"no name, no voice, just access."',
    'Crouch in a corner, spread and held, while your opponent lists who\'s next to use you.',
    'Ask to be bred by strangers—then simulate it happening in a pile of limbs.',
    'Tie yourself open and beg to be left in a hallway or closet for use.',
    'Grind into a toy while wearing a sign that says "open hole, closed mouth."',
    'Get placed on display, tied and plugged, in the center of the room for 10 minutes.',
    'Simulate being passed from one person to another—each thrust gets a degrading phrase.',
    'Be face-fucked (real or simulated) while being slapped repeatedly on your dripping hole.',
    'Get whipped while chanting "this cunt/ass is for them, not for me."',
    'Say "I\'m the room\'s cumrag," then lie down and wait to be filled.',
    'Be fully restrained, gagged, used, and ignored—no one checks if you\'re ready.',
    'Crawl to your opponent and beg them to pass you around—like you\'re nothing.',
    'Present your mouth, pussy, and ass at once and ask, "Which hole deserves to cry?"',
    'Stay edge-denied while your opponent simulates others preparing to take you.',
    'Be spit on, then ordered to beg for a line of men to finish in you.',
    'Suck a toy soaked in lube or spit while imagining every user before you.',
    'Plug yourself and edge with clamps or pressure—every moan triggers a ruined orgasm threat.',
    'Stay with both hands bound and a gag in until your body begs without permission.',
    'Be used, then gagged with the toy that ruined you.',
    'Hold a squat with a toy inside until your legs shake—fall and get spanked.',
    'Lay across a bench, legs held open, hands behind your back—wait for use that never comes.',
    'Simulate a faceless gangbang using multiple toys—moan for each one that "finishes."',
    'Let your opponent write "hole 1," "hole 2," "hole 3" across your body.',
    'Be passed from hand to hand—every new touch must be met with "thank you, next."',
    'Lie in the center of the floor, dripping, fully still, as if waiting for your turn again.',
    'Crawl to the edge of a doorway and beg for use while restrained.',
    'Simulate being used by a team—mouth, hands, ass, pussy all claimed.',
    'Stay plugged and nipple-clamped while on your knees, hands up.',
    'Edge three times in a row while balancing something on your lower back.',
    'Wear a gag and blindfold while holding a toy in your ass and one in your mouth.',
    'Be told to moan like you\'re being used by five different men—louder each time.',
    'Stay kneeling, holes exposed, while your opponent walks in and out, ignoring you.',
    'Simulate being stripped, used, and filmed—talk to the "camera" like a ruined toy.',
    'Gag in, arms tied, stay plugged and used while ordered to humiliate yourself.',
    'Crouch at the door and knock—when opened, offer your mouth, then turn and present your ass.',
    'Simulate a dogpile fuck—act like you\'re lost beneath strangers, dripping and objectified.',
    'Present each hole one by one, name them out loud, and ask how they should be ruined.',
    'Moan a countdown from 10—when you hit 1, your opponent ruins your orgasm on purpose.',
    'Stay tied face-down, plug in, arms bound tight. Be teased, slapped, then denied.',
    'Be instructed to beg for the mess of others to be left inside you.',
    'Suck a plug while riding another—failure to stay silent = full denial.',
    'Grind yourself into overstimulation until you break—then do 10 more strokes.',
    'Be left dripping in public risk space—plugged, messy, blindfolded—waiting.',
    'Ask to be "ruined in sequence": hole 1 stretched, hole 2 slapped, hole 3 gagged.',
    'Crawl nude to the nearest open window and press your hole to the glass—do not move until called back.',
    'Be told, "You don\'t get a punishment this round—the winner gets to do whatever they want to you." (Winner\'s choice)',
    'Plug in, gag in, hands tied, and walked into a bathroom stall or locked closet—left for 3 minutes.',
    'Present your ass to your opponent. If they say "no," you must crawl away and beg for a second hole to offer.',
    'Remain in a doorway fully exposed—your clothing is across the room, and the door is unlocked.',
    'Be forced to edge with your face down in her panties—no touching her, just whimpering.',
    'Stay frozen in plank position while your hole is fingered, paddled, or watched.',
    'Sit on a chair facing away, legs spread, back arched, begging to be seen.',
    'Kneel beside your opponent\'s ass or crotch and stay perfectly still, plug in, tongue out.',
    'Lie naked and gagged while your opponent explains in detail how they\'ll ruin you later.',
    'Plugged, with clamps on, you must crawl through a dirty or uncomfortable area—crying = reset.',
    'Wear a sign that says "Property of the Winner"—they get one free use of any hole. (Winner\'s choice)',
    'Edge while staring at a locked door—if you make a sound, your opponent walks away.',
    'Stay tied, dripping, in an unused room. You may not call out—you\'re only used if someone decides to return.',
    'Simulate being taken on camera—say "this is for everyone" while holding your holes open.',
    'Be blindfolded and restrained. Someone walks around you silently for 5 minutes before acting.',
    'Beg to be leashed and paraded somewhere risky—if denied, beg harder and accept punishment for wanting it.',
    'Forced to present yourself with your hands tied behind your knees. Stay locked like that until freed.',
    'Stay nude, plugged, and exposed behind a half-open curtain. You may only breathe through your nose.',
    'Plugged in both holes, told to "stay leaking"—each drip is a point toward your next punishment.',
    'Be placed over a table with your face down and ass up, held in place for as long as the opponent desires.',
    'Stand with legs spread and a toy in your mouth—don\'t move until it falls.',
    'Wear a vibrating plug during your next three rounds—orgasm = punishment escalation.',
    'Present your face and ass simultaneously—your opponent chooses which one gets used, which one gets hurt.',
    '"No rules for the next round"—your opponent decides everything. (Winner\'s choice)',
    'Be gagged, stripped, blindfolded, and displayed in the hallway.',
    'Cry while begging to be denied. If tears fall, you\'re forced to thank them between sobs.',
    'Stay plugged and mouth open, lying on the floor. If someone spits, you swallow.',
    'Place one hand in your hole, one on your throat, and hold your breath until they count down.',
    'Plug in, gag in, climb onto a counter, and pose like an offering dish.',
    'Be forced to pose in five degrading positions while leaking down your thighs.',
    'Crawl to your opponent and say "I belong to your hole." They choose how you\'re used. (Winner\'s choice)',
    'Simulate having to explain your condition to a stranger—"I\'m plugged, stretched, and I\'m not allowed to stop."',
    'Crouch over a bowl and beg to piss while someone watches from above.',
    'Your opponent locks you in one position—if you move, you\'re punished twice.',
    'Lick up the trail of your own leak from the floor to the base of the plug.',
    'Be denied until your whole body is shaking, then tied down and left untouched.',
    'Face buried in fabric, moaning into it while your hole is slowly stretched wider than you\'ve ever gone.',
    'Spread yourself while they apply clothespins—any noise results in another.',
    'Put your mouth over the toy you\'re about to be fucked with—gag on it, then take it inside.',
    'Ask your opponent to name your holes. Once they name them, you must only refer to them that way for the rest of the game.',
    'Simulate being force-fed cum or piss and made to wear it until dismissed.',
    'Crawl to the punishment zone completely exposed—if you hesitate, your next hole is doubled.',
    'Lay face-down over a bench, arms tied, moaning "I\'m just a fuck toy."',
    'Beg to have your hole ruined past repair. They choose what that looks like. (Winner\'s choice)',
    'Tape a toy into your ass and kneel, drooling, waiting to be called.',
    'Simulate someone using your face while someone else stretches your hole—you must speak between gags.',
    'Be placed in a corner with your hole exposed and a timer. Anyone may use you once per minute.',
    'Simulate someone pulling out and another replacing them—gasp each time with thanks.',
    'Plug in, clamps on, face covered—be told to leak until they say "stop."',
    'Lie face up with one hole dripping and one gagged—beg to be used in the third.',
    'Gag in, plug in, eyes closed—opponent may use, ignore, or command you without warning.',
    'Stay tied with your hole facing a door. If anyone enters, you\'re not allowed to flinch.',
    'Ask, "What do you want to take from me tonight?" and obey without hesitation. (Winner\'s choice)',
    'Fully plugged and blindfolded, be whispered to for 5 minutes while being touched randomly.',
    'Be carried or dragged to your punishment spot—strip silently as you arrive.',
    'Have a toy used on you until you beg for the pain over the pleasure.',
    'Keep your hole open, plug beside you—you may not insert it until you\'re slapped.',
    'Crawl to the base of a piece of furniture—stay there in service pose until used or dismissed.',
    'Kneel gagged with your arms behind you. Every time you\'re tapped, offer a new hole.',
    'Simulate a forced confession—describe how it feels to be ruined while your hole is stretched.',
    'Be plugged, bound, hooded, and made to smell your last use—stay motionless while it\'s replayed.',
    'Stand naked, arms up, while your opponent describes your body like a used object.',
    'Ask your opponent to decide which hole gets owned and which gets shared.',
    'Take five ruined orgasms in five positions—if any are too soft, you must repeat all five.',
    'Simulate being wiped down after use—smeared, wiped again, then plugged.',
    'Gag in, tongue out, crawling—every surface must be sniffed and respected like a master\'s mess.',
    'Rub yourself against a surface until you edge—orgasm equals a punishment chosen by your opponent. (Winner\'s choice)',
    'Stay face down, hands flat, legs open—be used silently, then ordered not to clean up.',
    'Ask to be used until your hole forgets its shape.',
    'Wear your opponent\'s underwear while being punished—every moan must be a thank-you.',
    'Get used from behind while forced to read a degrading script aloud—if you stutter, you\'re punished.',
    'Lie curled up, toys inside you, gag in—\'waste on standby.\'',
    'Ask to be decorated: clamps, ropes, plugs, scribbles—stand there like a used-up centerpiece.',
    'Be tied to a shower rod, plug in, water running—"cleaned without care."',
    'Crawl in a circle three times, crying, then kneel in place until your name is called.',
    'Gag in, leash on, plug vibrating—stay like that while holding a humiliating pose.',
    'Simulate being led onto a stage—lights on you, hole spread, no voice.',
    'Ask for a hole inspection. Every note your opponent gives must be repeated back.',
    'Sit on your knees, thighs dripping, mouth closed. You must earn the right to speak.',
    'Remain naked and plugged in front of an open window for one full orgasm denial cycle.',
    'Tie your ankles and wrists behind your back—stay ass up until your opponent releases you.',
    'Present your hole for fucking, plug it yourself after, and bow as if you were gifted.',
    'Ask to be spat on while crying. The first drop must be swallowed.',
    'Keep your ass gaping, plug beside you, while you say "this is what\'s left of me."',
    'Edge while listening to your own humiliation on a recording—crying is encouraged.',
    'Stay curled up, arms around your legs, while your opponent rubs your plug between your thighs.',
    'Be used in one hole, denied in another, gagged, and forced to imagine being taken by ten.',
    'Simulate being locked in chastity—hole sealed, mouth full, begging to be emptied.',
    'Present yourself like an offering plate—whichever hole drips first, gets used next.',
    'Crawl to the bathroom, kneel beside the urinal, and ask to be filled or flushed. (Winner\'s choice)',
    'Stay tied to a bed or pole until your opponent tells you what you\'ve done wrong.',
    'Describe your body like a ruined tool—each sentence must end in "please use me again."',
    'Present yourself upside down—hole in the air, dripping, mouth held wide open.',
    'Wear a plug with a tail or leash. Crawl to your opponent and beg to be walked like property.',
    'Gag in, plug out, ask to be held open while your opponent recites your failures.',
    'Simulate being taken by a group—respond to each imaginary user with a different word of gratitude.',
    'Be used in one hole until you leak, plugged instantly, then turned and used in the next.',
    'Offer every hole, say what it\'s best for, and why you no longer deserve to choose.',
    'Ask your opponent to ruin you in their favorite way—and accept it without hesitation. (Winner\'s choice)'
  ]
}; 