// punishments.js
// Expanded punishment lists for each difficulty level

const PUNISHMENTS = {
  Easy: [
    "Sit on your hands until your next turn.",
    "Speak only when spoken to for the next full round.",
    "Remove one sock with your teeth.",
    "Say 'I am [opponent\'s name]\'s toy' three times out loud.",
    "Hold a penny between your butt cheeks for one full turn.",
    "Kiss the floor.",
    "Let your opponent rename you for the next 3 rounds.",
    "Stay on your knees for the next turn.",
    "Let opponent tuck your shirt into your underwear.",
    "Draw a small heart or collar on your chest or neck with a marker.",
    "Hold your tongue out for 30 seconds without laughing or pulling it back in.",
    "Whisper 'please punish me' in your opponent\'s ear.",
    "Text yourself 'I\'m a good little pet' and show your opponent.",
    "Balance an object (book, cup, etc.) on your head for 1 minute.",
    "Speak in third person for the next two turns.",
    "Roll over and beg like a dog.",
    "Let your opponent give you a silly nickname for the next hour.",
    "Keep your hands behind your back until your next action.",
    "Put on an item of clothing backward.",
    "Hold an ice cube in your hand while staying silent.",
    "Let your opponent boop your nose and say 'mine.'",
    "Stand in the doorway like you\'re being displayed for 30 seconds.",
    "Rub your own face like you\'re being petted.",
    "Stick out your tongue and say 'I deserve worse.'",
    "Write 'loser' on your foot and show it.",
    "Say 'I\'ll be good' every time your opponent looks at you for the next round.",
    "Only crawl to change your position until your next turn.",
    "Nod and say 'yes, [title]' every time you\'re spoken to until the next round.",
    "Let your opponent adjust your posture exactly how they want.",
    "Keep your eyes lowered until you\'re given permission to look up.",
    "Make up a cringey pet name for yourself and say it out loud.",
    "Spell the word 'obedient' using your body like you\'re in a cheer routine.",
    "Say 'I\'m a little shy toy' while hiding your face.",
    "Let your opponent take a picture of your most embarrassed face (non-nude).",
    "Read aloud a mock 'confession' written by your opponent.",
    "Wag your butt like a tail and pant.",
    "Balance a small item on your nose like a puppy.",
    "Crawl in a circle twice and bark softly.",
    "Purr while being pat on the head for 10 seconds.",
    "Wear something on your wrist or neck like a leash for one turn.",
    "Hold your arms out straight for 45 seconds.",
    "Sit cross-legged and keep your hands flat on your thighs.",
    "Stand facing the wall with hands behind your head for 1 minute.",
    "Lie on the floor with your hands behind your back for 30 seconds.",
    "Put an ice cube in your sock until it melts or the next turn.",
    "End every sentence with 'if I\'m allowed.'",
    "Recite the alphabet backward (or try).",
    "Repeat 'I serve. I obey. I blush.' three times.",
    "Say your opponent\'s name in a flirty voice 5 times.",
    "Make up a theme song about being punished and sing the chorus.",
    "Stay silent until your opponent snaps their fingers.",
    "Ask for permission to sit, even if you don\'t plan to.",
    "Stand with your arms behind your back while your opponent circles you.",
    "Let your opponent pick your pose for 1 minute and freeze like a statue.",
    "Thank your opponent for punishing you, and mean it.",
    "Say 'I secretly like being punished' in your most embarrassed voice.",
    "Mime getting spanked while looking bashful.",
    "Blush on command. If you can\'t, fake it.",
    "Describe your 'most humiliating fantasy' using only five words.",
    "Write 'punishable' on your hand and keep it visible for the next round.",
    "Crouch like a bunny and stay still until your opponent tells you to move.",
    "Be 'on display'—pose cutely or suggestively for 30 seconds.",
    "Meow twice every time you move until your next turn.",
    "Sniff your own shirt collar or armpit like you\'re being checked.",
    "Lick your own hand and pretend it was someone else\'s.",
    "Sit with your legs spread wide (clothed) and hold position for 1 minute.",
    "Keep your arms above your head for 1 full turn.",
    "Use your toes to pick up an object and hand it to your opponent.",
    "Place a small object under your shirt and let it stay there for 2 rounds.",
    "Sit on the ground with your knees up, arms wrapped around them, and rock for 30 seconds.",
    "Speak in a fake accent for the next 3 sentences.",
    "Make up a motto for yourself as a submissive.",
    "Say your favorite dessert in the sexiest voice you can manage.",
    "Narrate your own punishment like it\'s a nature documentary.",
    "Say 'I lost because I\'m cute and weak' with a giggle.",
    "Keep your palms visible and open at all times until your next turn.",
    "Sit exactly where your opponent points—floor, couch, etc.",
    "Say 'Whatever you say, I\'ll do' three times in a row without smiling.",
    "Stay in physical contact with your opponent (hand, foot, shoulder) until next round.",
    "Ask 'What would please you most right now?' and accept their answer respectfully.",
    "Name 3 places you\'d hate to be punished in public. Say them out loud.",
    "Pretend to be scolded and respond with 'Yes, I deserve it' three times.",
    "Stick your tongue out, cross your eyes, and say 'I\'m so dumb, it\'s cute.'",
    "Rate your own obedience on a scale from 1 to 10—but explain why it\'s so low.",
    "Say: 'Punishments make me wet/hard and ashamed.' Then cover your face.",
    "Let your opponent 'reposition' you like a doll or a display figure.",
    "Place an object on your back and try to stay still so it doesn\'t fall.",
    "Bark each time your opponent says a command word (they choose it).",
    "Crawl to your opponent with something in your mouth and drop it at their feet.",
    "Put your hands together like paws and stay that way until the end of the turn.",
    "Stand on your toes for 30 seconds. Each second you wobble = one extra second.",
    "Lay belly-down and stay perfectly still for 45 seconds.",
    "Sit with one hand behind your back and one on your mouth for one full turn.",
    "Put your feet or hands flat on a cold surface and keep them there for 1 minute.",
    "Push your hands between your thighs and hold them there—no fidgeting.",
    "Recite a made-up school pledge for 'The Academy of Obedience.'",
    "Narrate your defeat like you\'re the sad loser in a drama.",
    "Pretend you\'re auditioning for the role of 'perfect toy.' Sell it.",
    "Try to say 'I don\'t deserve this' without laughing or blushing.",
    "Choose one body part and confess something humiliating about it.",
    "Count to 50 in a whisper while balancing on one foot.",
    "Hold your breath while your opponent counts to 20.",
    "Slowly lower yourself to your knees over a count of 10.",
    "Clap once every 5 seconds for a full minute—each clap must be followed by 'Good toy.'",
    "Ask your opponent for a 15-second task and obey it immediately, no questions.",
    "Rub something cold on your lower back and describe how it feels.",
    "Sit still while your opponent hovers their hand an inch from your face—don\'t move.",
    "Close your eyes and identify 3 textures touching your body.",
    "Allow your opponent to breathe or whisper something into your ear.",
    "Press your tongue to something cold or smooth and say how it tastes.",
    "List three punishments you\'re dying to receive, and then ask to be denied all of them.",
    "Hold your hand near your own thigh or crotch—but never make contact.",
    "Beg to be allowed to touch your favorite spot. If they say no, say 'Thank you.'",
    "Place your own finger on your lips and whisper, 'Not yet.'",
    "Write 'edge' on your palm and stare at it silently for one full turn.",
    "Act like a wind-up toy: let your opponent 'wind' you up, then do 5 silly movements.",
    "Pose like a calendar model for pets—sassy, smug, or cute.",
    "Ask your opponent for a reward… then tell them why you don\'t deserve it.",
    "Declare what 'level' submissive you are, like it\'s a video game stat.",
    "Roll an invisible die and pretend it determines your fate—react accordingly.",
    "Act like a robot taking orders from your opponent for one turn.",
    "Sit cross-legged with your tongue out for 30 seconds.",
    "Every time your opponent speaks for the next minute, you must whisper 'yes.'",
    "Mime licking your opponent\'s boots, slowly and dramatically.",
    "Ask, 'Can I be punished harder next time?'",
    "Make your best 'begging face' and hold it for 10 seconds.",
    "Try to balance a pillow on your head while crawling across the room.",
    "Say 'I need structure. I need discipline. I need you.'",
    "Crouch like a frog and stay there for one minute.",
    "Give yourself a nickname and beg your opponent to call you by it.",
    "Say 'I\'m trained and tamed' while touching your collarbone.",
    "Press your forehead to the floor for 20 seconds.",
    "Stay completely still while your opponent walks around you.",
    "Spell the word 'humiliate' out loud while looking at the floor.",
    "Ask to be leashed, even if no leash is present.",
    "Count from 10 to 1 in a moaning, drawn-out voice.",
    "Let your opponent 'inspect' you without speaking.",
    "Pretend to be activated by a single word your opponent picks.",
    "Gently tap your own cheek every time you mess up a sentence.",
    "Ask your opponent to call you by your most embarrassing pet name.",
    "Lay flat on your back and pretend to be turned off until your opponent reactivates you.",
    "Make a sound effect for every movement you make for the next minute.",
    "Bow every time you enter or leave a space for the next 2 turns.",
    "Stay one step behind your opponent wherever you go for one round.",
    "Whimper once every 15 seconds until told to stop.",
    "Say, 'I\'m ready to be molded into whatever you need.'",
    "Shake your butt three times and say 'Trained and proud.'",
    "Bite your finger and say 'I\'m naughty and I know it.'",
    "Ask, 'Can I prove myself to you again?'",
    "Say your opponent\'s name like a secret crush.",
    "Let your opponent assign you a simple task—and thank them afterward.",
    "Act like you\'re being patted and say 'good toy' every 5 seconds.",
    "Say 'Please don\'t make me enjoy this,' then smile.",
    "Crawl to your opponent and rest your head on their knee.",
    "Repeat 'I am shaped by your hands' until interrupted.",
    "Lick your own lips slowly and say 'I\'ll behave.'",
    "Pace in a circle like a trained show pet.",
    "Say 'This is humiliating, and I love it.'",
    "Act like you\'re being scolded and nod shamefully.",
    "Make your body into a letter 'S' on the floor.",
    "Hold your breath while being stared at.",
    "Ask for feedback on your posture.",
    "Keep your fingers laced behind your head until your opponent lets you go.",
    "Meow every time you change position until the next round.",
    "Hold one shoe in your mouth handle (or pretend to).",
    "Keep your hands folded like a good student.",
    "Ask for 'just one small punishment' in the cutest voice you can.",
    "Shiver on command.",
    "Let your opponent rest their foot or hand on you for 1 minute.",
    "Announce 'I am nothing but a canvas for your power.'",
    "Tuck your hands into your waistband and walk 3 steps.",
    "Say 'I need structure' and bow your head.",
    "Rest your chin on your opponent\'s hand or lap (if permitted).",
    "Keep your mouth open for 15 seconds while kneeling.",
    "Chant 'obedient, obedient, obedient' quietly.",
    "Rub your face on the carpet or couch and say 'pet behavior.'",
    "Let your opponent give you a new role: pet, object, toy, etc.",
    "Ask your opponent for instructions on how to sit.",
    "Say 'I am learning to listen' while staying silent.",
    "Place your hands flat on a table and don\'t move them for 2 minutes.",
    "Flop on the ground and say 'I\'m yours to pick up.'",
    "Ask for your punishment in rhyme form.",
    "Hum a lullaby while curled into a ball.",
    "Repeat 'yes' after every statement your opponent makes for 1 round.",
    "Crouch and stare at the floor like you\'ve been put in time out.",
    "Let your opponent pose you like a doll and hold still.",
    "Ask to be told what you\'re good for.",
    "Gently slap your own cheek and whisper 'Obey.'",
    "Make your lips into a kissy face until dismissed.",
    "Say 'I am trained and treasured' like a mantra.",
    "Repeat 'I am below you' softly and reverently.",
    "Act like you\'re being auctioned and describe your 'features.'",
    "Lay with your arms above your head and stay still.",
    "Repeat 'please use me' until interrupted.",
    "Let your opponent tap your nose every time you speak.",
    "Stick your tongue out until your opponent says 'down.'",
    "Mime being walked on a leash.",
    "Kneel with your hands in prayer and whisper 'I obey.'",
    "Rub your own thighs and say 'I\'m patient.'",
    "Blink twice slowly and say 'I\'m thinking obedient thoughts.'"
  ],
  Medium: [
    "Plug yourself while facing a mirror, then ask your reflection for permission to touch.",
    "Crawl with a clothespin clamped to your tongue—if it falls off, restart.",
    "Stay fully still while being called nothing but a hole.",
    "Be blindfolded and rotated before being placed in a new position—hold it.",
    "Edge while kneeling on something uncomfortable—orgasm equals loss of next turn.",
    "Ask your opponent for instructions with your mouth full and hands tied.",
    "Crawl toward your opponent, leaking, and thank them for everything they haven't done yet.",
    "Be bound and placed on display for five full minutes—no interaction, only exposure.",
    "Plug in, say nothing, and accept whatever gets written on your body.",
    "Say 'I'm here to take more than I think I can handle'—then open your legs.",
    "Stay pressed against the floor with your ass raised—every noise you make adds a slap.",
    "Crawl backward while repeating 'this is the only way I move.'",
    "Sit with a toy in your mouth and a second in your hand—decide which one gets used.",
    "Present your hole silently—your opponent says 'yes' or 'no.'",
    "Simulate being gagged by their body—repeat 'thank you for my silence.'",
    "Edge with the plug in halfway—moan if it slips deeper.",
    "Cry while being called nothing but 'thing' or 'toy.'",
    "Be ordered to present yourself for one final punishment, then denied.",
    "Stay fully bound for the length of a full round, leaking and ignored.",
    "Ask your opponent to tell you what your body is worth to them.",
    "Gag yourself with an object and crawl to the punishment zone.",
    "Repeat 'this is what I asked for' while holding yourself open.",
    "Kneel at the door to the room, naked and silent, until let in.",
    "Grind your hips into the floor and say 'this is all I know how to do.'",
    "Simulate being led onstage for auction—repeat your holes and their conditions.",
    "Let your opponent describe you like an item they're about to sell.",
    "Lick or sniff your own plug before inserting it back in.",
    "Crawl to the mirror and beg your reflection for forgiveness.",
    "Plugged, gagged, and on all fours—your opponent lists your failures.",
    "Be left blindfolded in an exposed position for a countdown.",
    "Hold your own ass open for 30 seconds while describing how it feels to be seen.",
    "Say 'I will learn to take it' ten times between each tap or strike.",
    "Stay kneeling with a toy pressed against your face—you don't get to use it.",
    "Present your mouth as your only usable hole for the next two rounds.",
    "Simulate being shared by two people—one for each hole.",
    "Ask for the right to cum. If denied, stay silent and cry.",
    "Say 'I am not entitled to release' while edging slowly.",
    "Be restrained and used for a countdown with no control.",
    "Be denied every request you make for one full round.",
    "Crawl naked across a cold floor to beg for use.",
    "Sit with your ass on the ground, legs up, hands behind you—wait like a discarded toy.",
    "Stay in one humiliating position for five full minutes while ignored.",
    "Recite three things you hate about your body—then offer that part.",
    "Gag yourself and keep it in until your opponent removes it.",
    "Say 'this hole is just a leftover' while exposing yourself.",
    "Be held in place, moaning, while your opponent does nothing.",
    "Simulate being turned down for use—crawl away apologizing.",
    "Stay silent while writing a degrading label on yourself.",
    "Edge with your back to your opponent—if you moan, you're punished.",
    "Kneel, mouth open, while your opponent drops something into it—real or simulated.",
    "Ask to be leashed and ignored. If denied, beg again.",
    "Crawl from the corner to the center of the room saying 'this is where I belong.'",
    "Present your least-preferred hole for the next punishment.",
    "Sit on your knees with your arms behind your back, toy in mouth, eyes closed.",
    "Moan 'use me' after every breath for one full minute.",
    "Simulate someone using you just to leave a mess—plug in after.",
    "Plug in and sit like furniture. You may not speak, move, or react.",
    "Ask what your opponent thinks you'd taste like—then offer that spot.",
    "Be told 'you're not worth it' after every edge.",
    "Crawl to your opponent and ask for the harshest punishment they won't give you.",
    "Be placed where your opponent steps over or around you like furniture.",
    "Stay silent while hearing how disgusting your use is.",
    "Plugged and dripping, ask to be cleaned, and be denied.",
    "Be forced to act out how you'd be ruined if they stopped caring.",
    "Press your body against something dirty and say 'this suits me.'",
    "Be allowed to touch yourself, but only while describing what your hole smells like.",
    "Simulate cleaning yourself with your own mouth, hands tied.",
    "Repeat 'I'm made to be emptied' as you touch yourself.",
    "Be gagged with a used toy and left in a room corner.",
    "Strip yourself while saying something humiliating with each item removed.",
    "Plug in and hold still while someone circles you three times.",
    "Crawl slowly with a toy held in your teeth.",
    "Kneel in front of a door and ask to be let in like an obedient pet.",
    "Be placed where you can hear others but not speak—stay there for 10 minutes.",
    "Cry while being given nothing to react to.",
    "Ask to be renamed, and write it across your chest.",
    "Sit naked in a chair while your opponent describes how you'd be sold.",
    "Plugged and exposed, say 'I'm nothing but leftover warmth.'",
    "Crawl in slow circles while begging each time you pass the mirror.",
    "Repeat 'I was better before I opened my holes.'",
    "Be asked to act like someone else's property—describe how they'd use you.",
    "Stay still while your opponent touches you like they're checking a toy's quality.",
    "Plug in, kneel, and whisper 'I'm ready to be discarded.'",
    "Strip slowly while reciting a degrading poem your opponent writes.",
    "Be left gagged in a position for display, not use.",
    "Ask to be given away. If refused, thank your opponent for still wanting you.",
    "Simulate being filmed without consent—respond like you're ashamed and afraid.",
    "Crawl with a toy inside you until you reach the wall—then freeze.",
    "Ask 'what am I now?'—your opponent answers, and you repeat it.",
    "Stay kneeling on a hard surface, face up, plug in, eyes closed.",
    "Write a degrading message on your ass or thigh and keep it visible.",
    "Plug in and be told to keep your hole leaking for the next round.",
    "Ask to be kept—your opponent decides what that means.",
    "Cry, edge, then beg not to be finished.",
    "Simulate being punished in public, describing each passerby's reaction.",
    "Sit with your arms behind your back, legs wide, and say 'I gave up my choices.'",
    "Plugged, blindfolded, whisper 'don't stop using me' repeatedly.",
    "Crawl into a closet or small space and stay hidden for five minutes.",
    "Ask your opponent what they want to ruin in you first.",
    "Be used silently, then left alone—your only task is to whisper, 'thank you for not caring.'",
    "Stay in a stress position (squat, plank, or wall sit) while gagged for two minutes.",
    "Ask your opponent to describe how they'd redesign your body if you had no say.",
    "Crawl backward with a plug in—if it falls out, you're punished and denied.",
    "Present yourself silently in the most degrading pose you can think of.",
    "Plugged and blindfolded, count to 30 out loud—one moan resets the count.",
    "Be told to offer your favorite hole for punishment. If you hesitate, a different one is chosen.",
    "Stay naked, kneeling, with an object balanced on your back—drop it and you're spanked.",
    "Gagged and kneeling, edge yourself with no hands.",
    "Sit on your hands with your knees apart—stay there for 5 minutes while being watched.",
    "Be walked across the room while gagged and plugged—crawl if refused.",
    "Moan on command three times—too soft or too loud means denial.",
    "Strip one piece of clothing each minute while begging to keep it.",
    "Lie face down and grind once for every degrading word your opponent says.",
    "Plugged and gagged, present your hole to the wall and stay like that for one full turn.",
    "Crawl under furniture or a low object as punishment.",
    "Stay leashed to a doorknob or bedpost and say 'I'm where I belong.'",
    "Be made to kneel while holding your hole open—hands shaking = 10 more seconds.",
    "Simulate being positioned by someone's hands—adjust yourself as if being arranged.",
    "Sit against the wall, plugged, and beg to be noticed.",
    "Repeat a degrading phrase while your opponent ignores you entirely.",
    "Press your body to a cold surface and edge while whispering 'thank you.'",
    "Be blindfolded and told to identify which hole is being touched or toyed with.",
    "Walk across the room with clamps on—say 'thank you' after each step.",
    "Present your most 'obedient' body part and ask to be used through it.",
    "Crawl in a circle around your opponent while saying 'I serve, I serve.'",
    "Be told to apologize to your body part for how it's treated—then slap it.",
    "Edge in silence. If you break, say 'this is why I'm not trusted.'",
    "Be plugged and denied, but required to stay in a begging position for 3 minutes.",
    "Crawl toward your opponent with a toy in your mouth—ask if they'll allow you to use it.",
    "Present your body part you like the least—your opponent gives it the most degrading name.",
    "Stay exposed and vulnerable while your opponent narrates a 'training report' about your performance.",
    "Plugged, hooded or blindfolded, sit in the corner and say 'not needed, not chosen.'",
    "Simulate being punished in front of a group—describe what they'd say as they watch.",
    "Sit with legs open, completely still, and let your opponent choose where they'd leave their mark.",
    "Be told to say 'thank you' for something you've never been thanked for before.",
    "Stay gagged and let your opponent spit on or into your body—real or imagined.",
    "Crawl to your opponent and ask them to choose a new name for your hole.",
    "Stand naked with your forehead against the wall and your arms behind your back.",
    "Be ordered to praise your punishment as if it were a gift.",
    "Stay exposed and restrained while your opponent reads something unrelated.",
    "Present your used hole and thank it for being available.",
    "Be told to moan or speak with someone else's name in your mouth.",
    "Walk or kneel wearing your plug, a degrading phrase taped to your thigh.",
    "Crawl from one side of the room to the other with an object in your mouth and no hands.",
    "Sit on the floor, hands behind you, and beg to be touched.",
    "Plugged and leashed, crawl toward your opponent and ask to be stored.",
    "Be told 'no punishment'—your opponent simply smiles and says they're saving it.",
    "Touch yourself for 30 seconds while being insulted—do not stop.",
    "Stay completely exposed in front of a mirror while repeating 'you chose this.'",
    "Ask to have your release taken away—thank them for locking it.",
    "Plug in, sit with your ass against the wall, and ask to be stretched more.",
    "Crawl to your opponent with a toy in your mouth, gag removed, say 'please replace it.'",
    "Ask to be used by your opponent's hands—but only get their words instead.",
    "Be denied access to all holes until you edge five times without release.",
    "Simulate being assigned to a use station—hands tied, plug in, exposed.",
    "Kneel with your mouth open and thank your opponent for anything they leave behind.",
    "Plug yourself while being insulted—hold it in until the last word lands.",
    "Stand fully naked, arms raised, and repeat 'this body serves better without shame.'",
    "Simulate being restrained in a closet or cage. Stay curled up until released.",
    "Be ordered to kneel facing a chair—your opponent may sit or leave you waiting.",
    "Hold yourself wide open and beg for denial.",
    "Crawl to a marked spot and moan five different ways until one is approved.",
    "Be told to reenact the last time you felt truly humiliated.",
    "Sit on your knees with your hands behind your head—any flinch = punishment.",
    "Edge while wearing a degrading item or article of clothing.",
    "Be called 'hole,' 'waste,' or 'thing' and respond 'yes' each time.",
    "Simulate being used in a locker room or backstage area.",
    "Press your ass or pussy to a wall and hold it there for 30 seconds.",
    "Ask for a degrading word to be whispered in your ear.",
    "Be stripped in silence. No words allowed until your punishment is over.",
    "Repeat the phrase 'take more from me' after each slap or thrust.",
    "Stay leashed to a heavy object and beg to be dragged.",
    "Crawl through something uncomfortable—carpet, floor, dirt—until dismissed.",
    "Wear a hood or blindfold and call yourself by your hole's name.",
    "Be slapped once for each second you hesitate in obeying your next command.",
    "Be stripped naked, hands behind your back, and asked to earn one item of clothing back.",
    "Lie face-down with your knees apart and beg for a second chance.",
    "Edge with your fingers in your mouth and your eyes locked on your opponent.",
    "Present your ass and ask what it's worth now—accept the answer.",
    "Stay gagged and motionless while your opponent lists what they could do to you.",
    "Be restrained face up, hole exposed, and left untouched while a timer runs.",
    "Plug in and repeat 'this hole belongs to you' until your voice shakes.",
    "Simulate being tied to a pole or post, dripping and frozen.",
    "Say thank you after each humiliation until told to stop.",
    "Be blindfolded, plugged, and forced to crawl in circles while begging to be stopped.",
    "Hold a toy in your mouth while kneeling with your ass against a cold surface.",
    "Sit with your legs open while a mirror reflects everything you are.",
    "Be ordered to imagine the worst thing someone could do to your hole—and repeat it aloud.",
    "Present your face for use, then your hole for punishment, then beg to trade them.",
    "Stay kneeling with your head lowered for ten minutes—if you lift it, restart.",
    "Stay naked and still with your tongue out, accepting whatever lands on it.",
    "Ask to be ruined, but only get denied—thank them anyway.",
    "Crawl backward until your hole touches a surface—hold still.",
    "Present yourself for inspection and say 'I'm not worth more than this.'",
    "Be restrained and toyed with until the tears come, then gagged and silenced.",
    "Ask to be used as furniture—your opponent decides how.",
    "Be leashed and walked naked across the room while plugged.",
    "Repeat 'I'm nothing but a toy' each time you're ignored.",
    "Plug in, kneel, and cry while being denied for one final round.",
    "Ask your opponent to finish you however they choose—and accept their answer without hesitation.",
    "Strip to underwear and kneel facing a wall for five minutes with hands behind your back.",
    "Crawl across the room naked and kiss the floor beneath your opponent's feet.",
    "Be denied touch for 10 minutes while gagged and tied at the ankles.",
    "Hold a plug in your mouth for five minutes—if it falls, you're spanked.",
    "Crouch in a corner, ass exposed, and remain silent for the next round.",
    "Walk the perimeter of the room nude, hands behind your head.",
    "Stay plugged while your opponent lists your flaws—no flinching allowed.",
    "Suck on a toy for 30 seconds while your opponent watches without expression.",
    "Be spanked five times, then thank your opponent and request five more.",
    "Edge yourself once, then stop mid-stroke and hold the position for 60 seconds.",
    "Strip completely and beg for clothing while your opponent says no.",
    "Be gagged and given a simple service task (like folding something) without using your hands.",
    "Sit naked on the floor while your opponent walks around you for one minute.",
    "Beg to be plugged, but your opponent chooses if you're allowed.",
    "Hold a clothespin between your lips while kneeling—drop it and you're punished.",
    "Press your chest to the ground and remain motionless for two minutes.",
    "Stay in dog position while your opponent decides if you're worth using.",
    "Be slapped once across your ass for every word you moan.",
    "Crawl a set path while wearing a degrading sign taped to your back.",
    "Gag yourself and beg with your eyes only—no words allowed.",
    "Edge once, then sit on your hands and wait until you're told to move.",
    "Be assigned a body part to present and offer it silently.",
    "Kiss your opponent's foot or knee while holding a humiliating pose.",
    "Hold a plug in your ass and balance something on your back for one minute.",
    "Recite a humiliating phrase three times while being spanked.",
    "Stay plugged and gagged in silence while your opponent ignores you.",
    "Ask to be used—if you stutter or hesitate, you're denied and punished.",
    "Grind against the floor without using your hands for 30 seconds.",
    "Stand in front of a mirror, fully naked, and describe yourself as a toy.",
    "Crawl backwards across the room while saying 'I am nothing but a hole.'",
    "Stay frozen with your ass in the air until you're dismissed.",
    "Be ordered to slap yourself once for each failed task this session.",
    "Edge with a clothespin on your tongue—make a sound and you're denied.",
    "Be given a countdown, but your opponent decides when it ends.",
    "Simulate being inspected—hold open your hole(s) and wait.",
    "Be assigned a degrading pet name and use it to refer to yourself aloud.",
    "Stay with your face to the wall while your ass is displayed for a full turn.",
    "Ask to be spanked. If denied, you must thank them for saying no.",
    "Be blindfolded and walked three steps—every misstep equals a strike.",
    "Put a toy between your thighs and hold it there while kneeling.",
    "Stay gagged, eyes down, and whisper 'please ruin me' once every 30 seconds.",
    "Edge to the point of trembling, then stop and say 'I don't deserve it.'",
    "Be used for face sitting (real or simulated) without being allowed to move.",
    "Press your forehead to the floor and stay still for five minutes.",
    "Write 'fucktoy' across your thigh and leave it visible for the rest of the round.",
    "Be forced to pick one hole to offer for the next round—no changing.",
    "Crawl with a toy in your mouth, plug in, and no hands.",
    "Present yourself silently and let your opponent choose what's used.",
    "Beg for permission to hold your own plug in—if denied, go without.",
    "Be told to repeat the phrase 'this hole isn't mine anymore' ten times.",
    "Hold yourself spread open while your opponent watches in silence.",
    "Be placed face down, ass up, and left there until someone says otherwise.",
    "Stay fully still while someone touches you—flinch and you're denied.",
    "Ask your opponent to mark you with a degrading word or name.",
    "Be spanked in sets of three—each set louder than the last.",
    "Cry while plugged and say 'thank you for making me this way.'",
    "Sit in a service pose and hold it for five minutes.",
    "Stay on your knees with a toy in your mouth—no hands, no noise.",
    "Plug in and grind against a pillow for 30 seconds—stop when told.",
    "Ask your opponent to tell you what your holes are for.",
    "Stay face down, ass up, and wait to be allowed to speak again.",
    "Be gagged and made to drool onto your own body.",
    "Stay tied or handcuffed while being denied for three full turns.",
    "Kiss a specific part of your opponent's body five times, then ask to be punished.",
    "Moan on command or be denied your next release.",
    "Present your body and say 'you may do whatever you wish to this.'",
    "Hold a humiliating pose in front of a mirror and describe what you see.",
    "Put on a leash or collar and beg to be walked or led.",
    "Edge while reading a degrading script out loud.",
    "Stay naked and kneel outside a closed door for two minutes.",
    "Ask for one of your holes to be 'retired'—that hole may not be used again this session.",
    "Be forced to wear an article of someone else's clothing while being punished.",
    "Plug in, sit on your hands, and beg with your voice only.",
    "Be told which hole you're not allowed to use for the next three turns.",
    "Ask to be renamed, then repeat that name every time you're addressed.",
    "Crawl with your hole dripping while your opponent watches and ignores you.",
    "Be left tied or leashed to an object for five minutes, alone.",
    "Edge while facing a wall—orgasm equals punishment.",
    "Simulate being inspected with gloved hands—react only with moans.",
    "Be gagged and kneel on the hard floor—stay until your legs hurt.",
    "Stay naked while someone circles you silently—no reaction allowed.",
    "Ask to be put in a humiliating position. If denied, you must hold still in shame.",
    "Sit in front of your opponent while they list your most humiliating traits.",
    "Say 'I belong to this hole' and point to whichever one is currently used.",
    "Stay fully still while being filmed (real or simulated)—any motion is punished.",
    "Be made to refer to yourself as 'it' until released.",
    "Plugged and gagged, crawl in a tight circle and beg to stop.",
    "Be assigned a pose and made to hold it until your body shakes.",
    "Present each hole one at a time and ask how it should be used.",
    "Repeat the phrase 'I serve my punishment' until told to stop.",
    "Be touched or teased and not allowed to make a sound.",
    "Plug in, hands tied, and wait to be spoken to again.",
    "Be made to count to 20 with your hole filled—moan on every even number.",
    "Say out loud what your punishment is and why you deserve it.",
    "Edge with cold lube, then be denied for one full round.",
    "Beg to be gagged again after being allowed to speak.",
    "Be blindfolded and punished in silence—each strike unexpected.",
    "Ask for one degrading word to be written on your body.",
    "Plug yourself and walk across the room without it falling—failure = restart.",
    "Kneel, fully exposed, and say 'I exist to serve and suffer.'"
  ],
  Hard: [
    "Insert a plug and stay kneeling, ass raised, for five full minutes—no movement.",
    "Spread your pussy or ass lips and say 'this is my use, not my choice.'",
    "Let your opponent slap your bare cunt or balls 10 times—thank them after each.",
    "Gag yourself with your underwear and kneel, mouth open, until told to close.",
    "Sit on a hard surface with your legs spread wide and hold that pose for 2 minutes.",
    "Edge while fully exposed—every moan earns a slap.",
    "Use a vibrator or pressure on your pussy/ass until tears start forming—then stop.",
    "Crawl on all fours, hole visible, and beg to be used without protection.",
    "Let your opponent spit into your hole (or pretend to), then seal it with a plug.",
    "Rub an ice cube against your clit or rim your own ass with it.",
    "Slap your own pussy or asshole and say 'obedience is learned through pain.'",
    "Face the wall, plug in, and stay there holding your cheeks apart.",
    "Let your opponent use a toy on your cunt/ass for 60 seconds without mercy.",
    "Show your hole to the opponent and say, 'I surrender to your will.'",
    "Lick your fingers clean after rubbing your pussy or playing with your ass.",
    "Smack your own clit or asshole each time you say 'I want to be broken.'",
    "Get your face sat on or stepped over—no flinching, no speaking.",
    "Beg for one orgasm you're not allowed to have—ask again, softer.",
    "Keep a toy inside and sit directly on it without moving for 3 minutes.",
    "Rub piss on your pussy lips or around your asshole—then hold eye contact.",
    "Lie back with your legs up and say 'I'll take what I'm given.'",
    "Let your opponent press their foot to your pussy or ass and grind.",
    "Edge using your finger, toy, or surface—don't stop unless told.",
    "Present your cunt/ass and offer your mouth at the same time—say 'choose your hole.'",
    "Push fingers inside yourself and hold them in while being degraded.",
    "Get tied up and left exposed while your opponent talks about what they could do.",
    "Crawl ass-first across the floor and beg to be filled.",
    "Lick a toy or finger while your ass or cunt is being spanked.",
    "Finger your pussy or ass while your opponent counts backwards from 30—stop on zero.",
    "Ask for your clit or hole to be punished directly—let them choose how.",
    "Cry out one humiliating phrase with every thrust or rub.",
    "Lay on your back, feet to your ears, and stay exposed until next round.",
    "Let your opponent insert a toy, remove it, then gag you with it.",
    "Moan while being used—if your pitch drops, you're punished.",
    "Show your hole in the mirror, say 'worthless and open,' and hold the gaze.",
    "Hold your cheeks apart while your opponent inspects your hole in silence.",
    "Be instructed to finger yourself in public risk position (balcony, near window).",
    "Suck on a plug or toy while holding your legs spread wide.",
    "Rub your asshole or clit and describe how each touch makes you more submissive.",
    "Lick something off your opponent's shoe or foot while plugged.",
    "Keep your tongue pressed to your clit or rim your own asshole for 30 seconds.",
    "Let your opponent write 'fuckhole' or 'cumdump' across your pelvis or lower back.",
    "Spank your own cunt or hole five times and say 'harder, please' after each.",
    "Crawl with a plug in and a toy in your mouth like it's a leash.",
    "Get slapped every time you hesitate while using your own hole.",
    "Pretend to be tied and pretend to resist—then cry 'please don't stop.'",
    "Rub your face against your own thighs, whispering 'this body is not mine.'",
    "Say 'this hole is yours to destroy' and finger yourself while you say it.",
    "Press your face into a dirty object (floor, sock, clothing) and beg to be used like it.",
    "Hold still while your opponent whips, spanks, or gropes you from behind.",
    "Get 30 spanks—each one must be counted aloud while maintaining position.",
    "Tie a rope or belt around your thighs to keep them spread, and kneel silently.",
    "Place a clothespin or clamp on a sensitive spot and hold still for 2 minutes.",
    "Edge while kneeling, ass in the air—stop instantly if you're touched.",
    "Say 'Please ruin my hole' while rubbing it and staying in eye contact.",
    "Grip your own throat or hair tightly while repeating 'I want to obey.'",
    "Present your hands to be bound, then sit motionless for five minutes.",
    "Spread your legs and stay still—your opponent will tease with no permission to squirm.",
    "Get paddled, whipped, or slapped with a chosen tool until you cry out three times.",
    "Say 'Use me. Break me. Make me beg.'—then obey the next command.",
    "Sit on a plug or insert a toy and recite your last three failures as a submissive.",
    "Your hole is off-limits for the rest of the game unless earned—write it on yourself.",
    "Stay silent for the next full round, even during punishment or stimulation.",
    "Accept a gag (or simulate one) and try to complete a degrading task while silenced.",
    "Edge yourself while counting to 100 out loud, one second at a time.",
    "Take 3 hard slaps on your cunt/ass every time you touch yourself without permission.",
    "Sit with a spoon of water on your head—spill it and start over—while your hole is teased.",
    "Say 'You're the reason I'm nothing but a body' and keep your head down.",
    "Ask for permission before every word spoken for 10 minutes—each failure earns a slap.",
    "Let your opponent smack your clit or asshole in rhythm while you count.",
    "Stay frozen with your tongue out—your opponent can spank, rub, or ignore you.",
    "Present your pussy or ass and be denied touch for 10 full minutes.",
    "Plugged and gagged, you must 'nod yes' to everything you're asked—even insults.",
    "Be restrained and edged for 5 minutes—but no begging allowed.",
    "Accept any two punishment tools (e.g. crop, paddle, hand) and take 15 swats total.",
    "Stand still while your opponent threatens to punish your favorite spot—but delays it.",
    "Let your opponent tie your hands, then edge you without release.",
    "Touch your hole as if you're about to be used—then freeze and beg not to be.",
    "Lay flat, fully exposed, while your opponent inspects you like a broken toy.",
    "Ask to be blindfolded or placed in the dark, then listen to your opponent move around you.",
    "Press your face into the wall while your opponent uses you or waits.",
    "Attempt to masturbate with no movement below the waist—failure = punishment.",
    "Be whipped, slapped, or scratched while repeating 'I will obey better.'",
    "Crawl with clamps on your nipples or ass cheeks, begging for mercy.",
    "Open your mouth and be slapped every time you try to close it.",
    "Let your opponent mark you with a humiliating label and punish any attempt to hide it.",
    "Rub your ass or pussy on a cold surface and moan for 30 seconds.",
    "Present your whole body, plug in, while being insulted and ignored.",
    "Edged five times in a row with no orgasm allowed—each denial earns a slap.",
    "Simulate being punished in public—moan and react as if being watched.",
    "Stay on display, legs spread, with clamps or pressure, until your opponent dismisses you.",
    "Obey a set of verbal commands without hesitation—hesitate once and you get paddled.",
    "Repeat 'I serve pain' with every stroke of your punishment.",
    "Stand with legs apart, arms above head, and let your opponent do as they like.",
    "Plug yourself and beg for it to be bigger.",
    "Suck a toy while someone teases your hole—failure to maintain pace = punishment.",
    "Hold your own wrists behind your back and don't move as you're played with.",
    "Beg your opponent to break your hole for their amusement.",
    "Stay gagged and plugged in corner, touching nothing, until a command is given.",
    "Ask 'How much pain do I deserve today?'—accept their answer fully."
  ],
  Extreme: [
    "Be hogtied with a plug in, gagged, and displayed for full inspection—no movement allowed.",
    "Crouch in the doorway, ass or pussy exposed, and beg to be walked like a fuckpet.",
    "Simulate a triple hole use: plug in, mouth gagged, hands spreading the remaining hole.",
    "Stay face-down, tongue out, while your opponent fucks or fists your ass or cunt.",
    "Plug yourself, crawl in a circle, and chant \"one hole, one purpose.\"",
    "Be bound and used without asking—you don't speak unless asked a question.",
    "Get slapped each time you breathe too loud while gagged, ass exposed.",
    "Open your legs, insert the largest toy you can handle, and hold for 3 minutes.",
    "Sit on the floor, hands behind your back, while your opponent verbally degrades your holes.",
    "Be face-fucked (or simulate it with toy/gag), no eye contact allowed, hands pinned.",
    "Edge five times while bound—moan once and you're denied release.",
    "Stay bent over with your ass held open—gag in, plug in, blindfolded.",
    "Receive a 3-hole slap: one for the mouth, one for the ass, one for the cunt.",
    "Crawl to a window or balcony, tongue out, and simulate begging for public use.",
    "Be tied with your legs over your head, stuffed with toys, and left to drool.",
    "Spread and hold your own holes open while your opponent circles you silently.",
    "Ask, \"Which hole deserves pain, and which deserves shame?\"—let your opponent decide.",
    "Have your name replaced—only respond to \"fuckhole,\" \"slut,\" or \"it\" for three rounds.",
    "Be used by two players (or simulate it): one takes your mouth, the other takes your hole.",
    "Crawl with clamps on your nipples or labia, plug inside, gag in, posture held.",
    "Get edged while standing on tiptoe—drop down early, take five hard slaps.",
    "Say, \"Use me until I break or blackout,\" while your opponent grips your throat.",
    "Stay silent for an entire scene. Moan once and your next orgasm is ruined.",
    "Lick the floor or a shoe while someone toys your hole—say \"this is my worth.\"",
    "Stay locked in place, fully stuffed, while your opponent drinks or relaxes nearby.",
    "Be placed kneeling with forehead to the ground—plugged, leashed, wrists tied.",
    "Simulate being spitroasted: one toy in mouth, one in ass or pussy, hands behind you.",
    "Kneel, hands on head, hole leaking—stay frozen while degraded or walked over.",
    "Receive impact play (spanks, slaps, crops) to a single spot until it bruises.",
    "Be blindfolded and edged until you're shaking, then denied without a word.",
    "Be stood against the wall, arms behind your back, while your hole is used or inspected.",
    "Hold a dildo or gag in your mouth and offer your body like furniture.",
    "Get used, then plugged, then told to crawl across the room without dripping.",
    "Gagged and spread, simulate being left on a stage for strangers to use.",
    "Grind your hole against an object while chanting a humiliating phrase—loudly.",
    "Crouch naked on a balcony or in front of a window, gag in, body exposed.",
    "Be given a countdown while fucked—if you don't cum on cue, you're punished.",
    "Simulate breath play while your face is pinned—gag in, hands restrained.",
    "Be placed ass-up over furniture, plugged, gagged, and unable to see who's watching.",
    "Grind into a pillow or toy while repeating \"fuckhole first, feelings never.\"",
    "Be called \"property,\" \"equipment,\" or \"livestock\" and treated accordingly—positioned, used, dismissed.",
    "Beg to be stretched beyond your current limit—then hold it until tears come.",
    "Stay fully plugged and gagged while your opponent pisses into a bowl beside you.",
    "Be leashed and walked into the bathroom, where you're ordered to kneel beside the urinal.",
    "Be held in front of a mirror, dripping, hole open, while told \"you're only a urinal now.\"",
    "Gagged with piss-soaked panties or cloth and made to sit, legs open.",
    "Watch your opponent piss—you're not allowed to speak, just kneel and stare.",
    "Be pissed on, then immediately spanked until red—'waste first, punishment second.'",
    "Lick up your own piss from the floor—slowly, in silence.",
    "Plug in, hole exposed, and beg to be refilled or ruined, loudly and repeatedly.",
    "Simulate a gangbang: lie on your back, legs wide, moaning as if holes are used in rotation.",
    "Be tied down, holes exposed, and forced to beg for \"just one more user.\"",
    "Get edged by multiple hands or toys—one mistake, and your orgasm is ruined.",
    "Hold a plug in your ass while your pussy is slapped 10 times—switch if male.",
    "Stay on your knees for 10 minutes, gagged, arms behind back—if you fall, you're caned.",
    "Simulate getting fucked while someone feeds your mouth—moan like it's your purpose.",
    "Be blindfolded, gagged, and laid out as a cumdump—\"no name, no voice, just access.\"",
    "Crouch in a corner, spread and held, while your opponent lists who's next to use you.",
    "Ask to be bred by strangers—then simulate it happening in a pile of limbs.",
    "Tie yourself open and beg to be left in a hallway or closet for use.",
    "Grind into a toy while wearing a sign that says \"open hole, closed mouth.\"",
    "Get placed on display, tied and plugged, in the center of the room for 10 minutes.",
    "Simulate being passed from one person to another—each thrust gets a degrading phrase.",
    "Be face-fucked (real or simulated) while being slapped repeatedly on your dripping hole.",
    "Get whipped while chanting \"this cunt/ass is for them, not for me.\"",
    "Say \"I'm the room's cumrag,\" then lie down and wait to be filled.",
    "Be fully restrained, gagged, used, and ignored—no one checks if you're ready.",
    "Crawl to your opponent and beg them to pass you around—like you're nothing.",
    "Present your mouth, pussy, and ass at once and ask, \"Which hole deserves to cry?\"",
    "Stay edge-denied while your opponent simulates others preparing to take you.",
    "Be spit on, then ordered to beg for a line of men to finish in you.",
    "Suck a toy soaked in lube or spit while imagining every user before you.",
    "Plug yourself and edge with clamps or pressure—every moan triggers a ruined orgasm threat.",
    "Stay with both hands bound and a gag in until your body begs without permission.",
    "Be used, then gagged with the toy that ruined you.",
    "Hold a squat with a toy inside until your legs shake—fall and get spanked.",
    "Lay across a bench, legs held open, hands behind your back—wait for use that never comes.",
    "Simulate a faceless gangbang using multiple toys—moan for each one that \"finishes.\"",
    "Let your opponent write \"hole 1,\" \"hole 2,\" \"hole 3\" across your body.",
    "Be passed from hand to hand—every new touch must be met with \"thank you, next.\"",
    "Lie in the center of the floor, dripping, fully still, as if waiting for your turn again.",
    "Tie up balls (or nipples if woman) to a weight and crawl around the room begging for use while restrained.",
    "Simulate being used by a team—mouth, hands, ass, pussy all claimed.",
    "Stay plugged and nipple-clamped while on your knees, hands up.",
    "Edge three times in a row while balancing something on your lower back.",
    "Wear a gag and blindfold while holding a toy in your ass and one in your mouth.",
    "Be told to moan like you're being used by five different men—louder each time.",
    "Stay kneeling, holes exposed, while your opponent walks in and out, ignoring you.",
    "Simulate being stripped, used, and filmed—talk to the \"camera\" like a ruined toy.",
    "Gag in, arms tied, stay plugged and used while ordered to humiliate yourself.",
    "Crouch at the door and knock—when opened, offer your mouth, then turn and present your ass.",
    "Simulate a dogpile fuck—act like you're lost beneath strangers, dripping and objectified.",
    "Present each hole one by one, name them out loud, and ask how they should be ruined.",
    "Moan a countdown from 10—when you hit 1, your opponent ruins your orgasm on purpose.",
    "Stay tied face-down, plug in, arms bound tight. Be teased, slapped, then denied.",
    "Be instructed to beg for the mess of others to be left inside you.",
    "Suck a plug while riding another—failure to stay silent = full denial.",
    "Grind yourself into overstimulation until you break—then do 10 more strokes.",
    "Be left dripping in public risk space—plugged, messy, blindfolded—waiting.",
    "Ask to be \"ruined in sequence\": hole 1 stretched, hole 2 slapped, hole 3 gagged.",
    "Crawl nude to the nearest open window and press your hole to the glass—do not move until called back.",
    "Be told, \"You don't get a punishment this round—the winner gets to do whatever they want to you.\" (Winner's choice)",
    "Plug in, gag in, hands tied, and walked into a bathroom stall or locked closet—left for 3 minutes.",
    "Present your ass to your opponent. If they say \"no,\" you must crawl away and beg for a second hole to offer.",
    "Remain in a doorway fully exposed—your clothing is across the room, and the door is unlocked.",
    "Be forced to edge with your face down in her panties—no touching her, just whimpering.",
    "Stay frozen in plank position while your hole is fingered, paddled, or watched.",
    "Sit on a chair facing away, legs spread, back arched, begging to be seen.",
    "Kneel beside your opponent's ass or crotch and stay perfectly still, plug in, tongue out.",
    "Lie naked and gagged while your opponent explains in detail how they'll ruin you later.",
    "Plugged, with clamps on, you must crawl through a dirty or uncomfortable area—crying = reset.",
    "Wear a sign that says \"Property of the Winner\"—they get one free use of any hole. (Winner's choice)",
    "Edge while staring at a locked door—if you make a sound, your opponent walks away.",
    "Stay tied, dripping, in an unused room. You may not call out—you're only used if someone decides to return.",
    "Simulate being taken on camera—say \"this is for everyone\" while holding your holes open.",
    "Be blindfolded and restrained. Someone walks around you silently for 5 minutes before acting.",
    "Beg to be leashed and paraded somewhere risky—if denied, beg harder and accept punishment for wanting it.",
    "Forced to present yourself with your hands tied behind your knees. Stay locked like that until freed.",
    "Stay nude, plugged, and exposed behind a half-open curtain. You may only breathe through your nose.",
    "Plugged in both holes, told to \"stay leaking\"—each drip is a point toward your next punishment.",
    "Be placed over a table with your face down and ass up, held in place for as long as the opponent desires.",
    "Stand with legs spread and a toy in your mouth—don't move until it falls.",
    "Wear a vibrating plug during your next three rounds—orgasm = punishment escalation.",
    "Present your face and ass simultaneously—your opponent chooses which one gets used, which one gets hurt.",
    "\"No rules for the next round\"—your opponent decides everything. (Winner's choice)",
    "Be gagged, stripped, blindfolded, and displayed in the hallway.",
    "Cry while begging to be denied. If tears fall, you're forced to thank them between sobs.",
    "Stay plugged and mouth open, lying on the floor. If someone spits, you swallow.",
    "Place one hand in your hole, one on your throat, and hold your breath until they count down.",
    "Plug in, gag in, climb onto a counter, and pose like an offering dish.",
    "Be forced to pose in five degrading positions while leaking down your thighs.",
    "Crawl to your opponent and say \"I belong to your hole.\" They choose how you're used. (Winner's choice)",
    "Simulate having to explain your condition to a stranger—\"I'm plugged, stretched, and I'm not allowed to stop.\"",
    "Crouch over a bowl and beg to piss while someone watches from above.",
    "Your opponent locks you in one position—if you move, you're punished twice.",
    "Lick up the trail of your own leak from the floor to the base of the plug.",
    "Be denied until your whole body is shaking, then tied down and left untouched.",
    "Face buried in fabric, moaning into it while your hole is slowly stretched wider than you've ever gone.",
    "Spread yourself while they apply clothespins—any noise results in another.",
    "Put your mouth over the toy you're about to be fucked with—gag on it, then take it inside.",
    "Ask your opponent to name your holes. Once they name them, you must only refer to them that way for the rest of the game.",
    "Simulate being force-fed cum or piss and made to wear it until dismissed.",
    "Crawl to the punishment zone completely exposed—if you hesitate, your next hole is doubled.",
    "Lay face-down over a bench, arms tied, moaning \"I'm just a fuck toy.\"",
    "Beg to have your hole ruined past repair. They choose what that looks like. (Winner's choice)",
    "Tape a toy into your ass and kneel, drooling, waiting to be called.",
    "Simulate someone using your face while someone else stretches your hole—you must speak between gags.",
    "Be placed in a corner with your hole exposed and a timer. Anyone may use you once per minute.",
    "Simulate someone pulling out and another replacing them—gasp each time with thanks.",
    "Plug in, clamps on, face covered—be told to leak until they say \"stop.\"",
    "Lie face up with one hole dripping and one gagged—beg to be used in the third.",
    "Gag in, plug in, eyes closed—opponent may use, ignore, or command you without warning.",
    "Stay tied with your hole facing a door. If anyone enters, you're not allowed to flinch.",
    "Ask, \"What do you want to take from me tonight?\" and obey without hesitation. (Winner's choice)",
    "Fully plugged and blindfolded, be whispered to for 5 minutes while being touched randomly.",
    "Be carried or dragged to your punishment spot—strip silently as you arrive.",
    "Have a toy used on you until you beg for the pain over the pleasure.",
    "Keep your hole open, plug beside you—you may not insert it until you're slapped.",
    "Crawl to the base of a piece of furniture—stay there in service pose until used or dismissed.",
    "Kneel gagged with your arms behind you. Every time you're tapped, offer a new hole.",
    "Simulate a forced confession—describe how it feels to be ruined while your hole is stretched.",
    "Be plugged, bound, hooded, and made to smell your last use—stay motionless while it's replayed.",
    "Stand naked, arms up, while your opponent describes your body like a used object.",
    "Ask your opponent to decide which hole gets owned and which gets shared.",
    "Take five ruined orgasms in five positions—if any are too soft, you must repeat all five.",
    "Simulate being wiped down after use—smeared, wiped again, then plugged.",
    "Gag in, tongue out, crawling—every surface must be sniffed and respected like a master's mess.",
    "Rub yourself against a surface until you edge—orgasm equals a punishment chosen by your opponent. (Winner's choice)",
    "Stay face down, hands flat, legs open—be used silently, then ordered not to clean up.",
    "Ask to be used until your hole forgets its shape.",
    "Wear your opponent's underwear while being punished—every moan must be a thank-you.",
    "Get used from behind while forced to read a degrading script aloud—if you stutter, you're punished.",
    "Lie curled up, toys inside you, gag in—\"waste on standby.\"",
    "Ask to be decorated: clamps, ropes, plugs, scribbles—stand there like a used-up centerpiece.",
    "Be tied to a shower rod, plug in, water running—\"cleaned without care.\"",
    "Crawl in a circle three times, crying, then kneel in place until your name is called.",
    "Gag in, leash on, plug vibrating—stay like that while holding a humiliating pose.",
    "Simulate being led onto a stage—lights on you, hole spread, no voice.",
    "Ask for a hole inspection. Every note your opponent gives must be repeated back.",
    "Sit on your knees, thighs dripping, mouth closed. You must earn the right to speak.",
    "Remain naked and plugged in front of an open window for one full orgasm denial cycle.",
    "Tie your ankles and wrists behind your back—stay ass up until your opponent releases you.",
    "Present your hole for fucking, plug it yourself after, and bow as if you were gifted.",
    "Ask to be spat on while crying. The first drop must be swallowed.",
    "Keep your ass gaping, plug beside you, while you say \"this is what's left of me.\"",
    "Edge while listening to your own humiliation on a recording—crying is encouraged.",
    "Stay curled up, arms around your legs, while your opponent rubs your plug between your thighs.",
    "Be used in one hole, denied in another, gagged, and forced to imagine being taken by ten.",
    "Simulate being locked in chastity—hole sealed, mouth full, begging to be emptied.",
    "Present yourself like an offering plate—whichever hole drips first, gets used next.",
    "Crawl to the bathroom, kneel beside the urinal, and ask to be filled or flushed. (Winner's choice)",
    "Stay tied to a bed or pole until your opponent tells you what you've done wrong.",
    "Describe your body like a ruined tool—each sentence must end in \"please use me again.\"",
    "Present yourself upside down—hole in the air, dripping, mouth held wide open.",
    "Wear a plug with a tail or leash. Crawl to your opponent and beg to be walked like property.",
    "Gag in, plug out, ask to be held open while your opponent recites your failures.",
    "Simulate being taken by a group—respond to each imaginary user with a different word of gratitude.",
    "Be used in one hole until you leak, plugged instantly, then turned and used in the next.",
    "Offer every hole, say what it's best for, and why you no longer deserve to choose.",
    "Ask your opponent to ruin you in their favorite way—and accept it without hesitation. (Winner's choice)"
  ]
}; 